version: "3.3"
services:
  web:
    restart: always
    build: .
    ports:
      - 80:80
    volumes:
      - ./recipe_app:/recipe_app
  # selenium-hub:
  #   image: selenium/hub
  #   container_name: selenium-hub
  #   ports:
  #     - 4444:4444
  # chrome:
  #   image: selenium/node-chrome
  #   volumes:
  #     - ./recipe_app:/recipe_app
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
